apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: sshtest

commonLabels:
  app: sshtest

resources:
  - deploy.yaml
  - service.yaml

configMapGenerator:
  - name: ssh-config
    files:
      - sshd_config=config/sshd_config
      - authorized_keys=config/authorized_keys

generatorOptions:
  disableNameSuffixHash: true
